/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappCallbackRouteImport } from './routes/whatsapp.callback'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppTagsRouteImport } from './routes/app.tags'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppConversationsRouteImport } from './routes/app.conversations'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppBroadcastsRouteImport } from './routes/app.broadcasts'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiPublicRunRemindersRouteImport } from './routes/api/public/run-reminders'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicMpesaWebhookRouteImport } from './routes/api/public/mpesa.webhook'
import { Route as ApiPublicAtWebhookRouteImport } from './routes/api/public/at.webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappCallbackRoute = WhatsappCallbackRouteImport.update({
  id: '/whatsapp/callback',
  path: '/whatsapp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsRoute = AppBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRunRemindersRoute = ApiPublicRunRemindersRouteImport.update({
  id: '/api/public/run-reminders',
  path: '/api/public/run-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpesaWebhookRoute = ApiPublicMpesaWebhookRouteImport.update({
  id: '/api/public/mpesa/webhook',
  path: '/api/public/mpesa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAtWebhookRoute = ApiPublicAtWebhookRouteImport.update({
  id: '/api/public/at/webhook',
  path: '/api/public/at/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/whatsapp/callback': typeof WhatsappCallbackRoute
  '/api/public/run-reminders': typeof ApiPublicRunRemindersRoute
  '/api/public/at/webhook': typeof ApiPublicAtWebhookRoute
  '/api/public/mpesa/webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/whatsapp/callback': typeof WhatsappCallbackRoute
  '/api/public/run-reminders': typeof ApiPublicRunRemindersRoute
  '/api/public/at/webhook': typeof ApiPublicAtWebhookRoute
  '/api/public/mpesa/webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/broadcasts': typeof AppBroadcastsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tags': typeof AppTagsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/whatsapp/callback': typeof WhatsappCallbackRoute
  '/api/public/run-reminders': typeof ApiPublicRunRemindersRoute
  '/api/public/at/webhook': typeof ApiPublicAtWebhookRoute
  '/api/public/mpesa/webhook': typeof ApiPublicMpesaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/automations'
    | '/app/broadcasts'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/insights'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/reminders'
    | '/app/settings'
    | '/app/tags'
    | '/app/templates'
    | '/app/whatsapp'
    | '/whatsapp/callback'
    | '/api/public/run-reminders'
    | '/api/public/at/webhook'
    | '/api/public/mpesa/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/automations'
    | '/app/broadcasts'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/insights'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/reminders'
    | '/app/settings'
    | '/app/tags'
    | '/app/templates'
    | '/app/whatsapp'
    | '/whatsapp/callback'
    | '/api/public/run-reminders'
    | '/api/public/at/webhook'
    | '/api/public/mpesa/webhook'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/automations'
    | '/app/broadcasts'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/insights'
    | '/app/logs'
    | '/app/onboarding'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/reminders'
    | '/app/settings'
    | '/app/tags'
    | '/app/templates'
    | '/app/whatsapp'
    | '/whatsapp/callback'
    | '/api/public/run-reminders'
    | '/api/public/at/webhook'
    | '/api/public/mpesa/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  WhatsappCallbackRoute: typeof WhatsappCallbackRoute
  ApiPublicRunRemindersRoute: typeof ApiPublicRunRemindersRoute
  ApiPublicAtWebhookRoute: typeof ApiPublicAtWebhookRoute
  ApiPublicMpesaWebhookRoute: typeof ApiPublicMpesaWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/callback': {
      id: '/whatsapp/callback'
      path: '/whatsapp/callback'
      fullPath: '/whatsapp/callback'
      preLoaderRoute: typeof WhatsappCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tags': {
      id: '/app/tags'
      path: '/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations': {
      id: '/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/broadcasts': {
      id: '/app/broadcasts'
      path: '/broadcasts'
      fullPath: '/app/broadcasts'
      preLoaderRoute: typeof AppBroadcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/run-reminders': {
      id: '/api/public/run-reminders'
      path: '/api/public/run-reminders'
      fullPath: '/api/public/run-reminders'
      preLoaderRoute: typeof ApiPublicRunRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpesa/webhook': {
      id: '/api/public/mpesa/webhook'
      path: '/api/public/mpesa/webhook'
      fullPath: '/api/public/mpesa/webhook'
      preLoaderRoute: typeof ApiPublicMpesaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/at/webhook': {
      id: '/api/public/at/webhook'
      path: '/api/public/at/webhook'
      fullPath: '/api/public/at/webhook'
      preLoaderRoute: typeof ApiPublicAtWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBroadcastsRoute: typeof AppBroadcastsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppBroadcastsRoute: AppBroadcastsRoute,
  AppContactsRoute: AppContactsRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLogsRoute: AppLogsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  WhatsappCallbackRoute: WhatsappCallbackRoute,
  ApiPublicRunRemindersRoute: ApiPublicRunRemindersRoute,
  ApiPublicAtWebhookRoute: ApiPublicAtWebhookRoute,
  ApiPublicMpesaWebhookRoute: ApiPublicMpesaWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
